fix typo ;)

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -56,7 +56,7 @@ then
                 --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
                 -jar "$JAR_FILE" --replace --set-exit-if-changed $changed_java_files
     then
-        echo "An error occured, aborting commit!" >&2
+        echo "An error occurred, aborting commit!" >&2
         exit 1
     fi
 else
